### ISSUE TITLE
Sharing 12oC seeds

### ISSUE THREAD

**Issue by BeepBot99** [Mesure73L/mesure.x10.mx#132]
### Issue Contents

Someone can just go, "Here's my seed, here's the solution for all the challenges."
Then, everyone could just copy it.
I think that it should be changed so that instead of getting to pick your seed, you can get a new seed if the challenge is too hard with your current one, but it will still be random.

**Comment by BeepBot99** [comment]
@Mesure73L Can we please do something about this issue?

**Comment by Mesure73L** [comment]
The whole point of being able to set your seed to whatever you want is so you can help your friends if they are stuck.

**Comment by BeepBot99** [comment]
Yes, but someone could just post the answers then.

**Comment by BeepBot99** [comment]
And, if a friend already has a working solution, then it can apply to any seed, not just theirs. Just because you and a friend do not have the same seed does not mean that it is any hardrer for your friend to help you. If anything, it might be easier, because if you have the same seed, then you are likely to just copy their answer without even trying.

**Comment by Mesure73L** [comment]
I don't know what your point is. If you really want to cheat there is documentation on the `CookieManager` class. Also, Twelve of Code is a personal challenge. If you don't want to do it legit, you don't have to. You could literally reverse engineer Twelve of Code to make a cheat extension if you really wanted to. And your point is that people could just share their seed and their answer, but you aren't thinking about the fact that people can just send the code and have you input your seed and it can figure it out for you. Another point, the reason I added the seed changer in the first place is because then I can change the seed to see what someone else could possibly see on it and make sure everything's possible.
